name: GH pages

on:
  push:
    branches:
      - 'master'

env:
  STX_NETWORK: mainnet

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add required Linux dependencies
        uses: ./.github/actions/linux-deps

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build prod
        run: yarn build

      - name: Run jest
        run: rm -rf docs/coverage && yarn test --coverage

      - name: Make coverage badge
        run: npx make-coverage-badge

      - name: Publish test coverage report
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: coverage
